// styles/blueprintStyles.js
// All shared inline style objects used across BlueprintDesign components.
// Import as: import S from '../styles/blueprintStyles';
// (or import { blueprintStyles as S } for named import)

const blueprintStyles = {
  toolBtn: {
    padding: "5px 12px",
    background: "#2d4a6e",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 500,
    whiteSpace: "nowrap",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  propInput: {
    width: "100%",
    padding: "4px 7px",
    border: "1px solid #334155",
    borderRadius: 4,
    fontSize: 11,
    background: "#0f172a",
    color: "#e2e8f0",
    boxSizing: "border-box",
  },
  panelLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: 1,
    margin: "0 0 8px",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  propLabel: {
    fontSize: 10,
    color: "#64748b",
    display: "block",
    marginBottom: 3,
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  floatingPanelLeft: {
    position: "absolute",
    top: 14,
    left: 60,
    width: 280,
    maxHeight: "calc(100% - 140px)",
    overflowY: "auto",
    background: "rgba(9,14,25,.82)",
    border: "1px solid rgba(148,163,184,.14)",
    borderRadius: 12,
    padding: 12,
    backdropFilter: "blur(8px)",
    boxShadow: "0 10px 30px rgba(0,0,0,.25)",
  },
  floatingPanelRight: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 260,
    maxHeight: "calc(100% - 30px)",
    overflowY: "auto",
    background: "rgba(9,14,25,.82)",
    border: "1px solid rgba(148,163,184,.14)",
    borderRadius: 12,
    padding: 12,
    backdropFilter: "blur(8px)",
    boxShadow: "0 10px 30px rgba(0,0,0,.25)",
  },
  floatingTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "#93c5fd",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  floatingSectionLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 1,
    margin: "8px 0 8px",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  floatingPaletteBtn: {
    width: "100%",
    textAlign: "left",
    padding: "8px 9px",
    border: "1px solid rgba(30,41,59,.9)",
    background: "#0f172a",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 11,
    color: "#cbd5e1",
    display: "flex",
    alignItems: "center",
    gap: 7,
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  floatingPrimaryBtn: {
    width: "100%",
    textAlign: "left",
    padding: "8px 10px",
    border: "1px solid #1d4ed8",
    background: "linear-gradient(180deg,#2563eb 0%, #1d4ed8 100%)",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 11,
    color: "#fff",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    gap: 7,
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  activeBuildPill: {
    background: "rgba(20,184,166,.14)",
    border: "1px solid rgba(20,184,166,.45)",
    color: "#99f6e4",
    borderRadius: 999,
    padding: "6px 10px",
    fontSize: 10,
    marginBottom: 10,
    lineHeight: 1.4,
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  floatingLabel: {
    display: "block",
    fontSize: 10,
    color: "#94a3b8",
    marginBottom: 3,
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  floatingInput: {
    width: "100%",
    padding: "5px 7px",
    border: "1px solid #334155",
    borderRadius: 4,
    fontSize: 11,
    background: "#0f172a",
    color: "#e2e8f0",
    boxSizing: "border-box",
  },
  infoCard: {
    padding: 10,
    borderRadius: 8,
    background: "#0f172a",
    border: "1px solid #334155",
    color: "#cbd5e1",
    fontSize: 11,
    lineHeight: 1.8,
    marginBottom: 10,
  },
  unityToolbar: {
    position: "absolute",
    top: 14,
    left: 14,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 6,
    borderRadius: 10,
    background: "rgba(28,35,48,.92)",
    border: "1px solid rgba(148,163,184,.18)",
    boxShadow: "0 8px 18px rgba(0,0,0,.28)",
    backdropFilter: "blur(6px)",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  unityToolBtn: {
    width: 34,
    height: 34,
    border: "1px solid #475569",
    background: "linear-gradient(180deg, #334155 0%, #1f2937 100%)",
    color: "#e5e7eb",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 18,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  unityToolBtnActive: {
    background: "linear-gradient(180deg, #60a5fa 0%, #2563eb 100%)",
    border: "1px solid #93c5fd",
    color: "#ffffff",
    boxShadow: "0 0 0 1px rgba(147,197,253,.2) inset",
  },
  smallPill: {
    fontSize: 11,
    background: "rgba(20,184,166,.14)",
    padding: "2px 10px",
    borderRadius: 20,
    color: "#99f6e4",
    border: "1px solid rgba(20,184,166,.35)",
    userSelect: "none",
    WebkitUserSelect: "none",
  },
  fullScreenWrapper: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    zIndex: 9999,
    display: "flex",
    flexDirection: "column",
    background: "#0f172a",
    overflow: "hidden",
  },
};

export default blueprintStyles;
export { blueprintStyles as S };
